# Generated by Django 3.2.14 on 2022-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('modifiedDate', models.DateTimeField(auto_now_add=True, verbose_name='수정날짜')),
            ],
        ),
    ]
